avhz/RustQuant

src/statistics/distributions/bernoulli.rs

#58 - doctests for bernoulli distribution
Bug-fix:
@avhz I made a bug fix to `kurtosis` of Bernoulli distribution based on [Wolfram-alpa](https://www.wolframalpha.com/input?i=bernoulli+distribution)
It appeared `+ 3.0` was missing.

Bernoulli distribution doctests

---

README.md

I'd advise against going for a `1.0.0` release too early. It's generally not recommended to release a `1.0.0` until all the dependencies you publicly expose are at least `1.0.0`. This is why most of the rust ecosystem isn't `1.0.0` yet

Target `v0.1.0` rather than `v1.0.0`

---

src/statistics/distributions/chi_squared.rs

#58 - doctests for chi-squared distribution
@avhz I have also implemented following functions along the way. Please have a look.
`inv_cdf`
`entropy` (based on [this ](https://en.wikipedia.org/wiki/Chi-squared_distribution): Properties > Entropy)

Chi-Squared distribution doctests

---

Cargo.toml

tests weren't working, adding macro feature flag for time dependency fixes it

fix: add macro feature flag for time dependency

---

src/time/calendars/denmark.rs

- General Prayer Day has been removed as public holiday from 2024.
- Added boilerplate tests for Denmark calendar
#142

Denmark General Prayer Day removed as public holiday, #142

---

src/curves/curve.rs
src/portfolio.rs

Fixes warnings in docs generations:
1) Two links in docs in functions in the Curve trait were not correctly referenced, so I added references to the functions they were trying to reference.
2) Two links in `portfolio.rs` had redundant information when referencing other parts of the code causing errors in docs generation so they were removed.
After this I don't see any warning in docs generation when I build locally, and I the links go to the functions.

fix warning in docs generation

---

examples/linear_regression.rs
src/data/yahoo.rs

This should close #29 
I was playing around with some stuff and wanted some more recent data so went ahead and implemented this

implemented get quote for yahoo finance api

---

src/time/calendars/botswana.rs
src/time/calendars/china.rs
src/time/calendars/hungary.rs
src/time/mod.rs

I decided to leave out the [Liberation Day](https://en.wikipedia.org/wiki/Liberation_Day_(Hungary)) since it was abolished before the stock exchange re-opened on 1990.
Similarly, the [1956 Revolution Day](https://en.wikipedia.org/wiki/Hungarian_Revolution_of_1956) only became a holiday after 1989.
Fixed extra whitespace.

Add calendar for Hungary

---

src/math/distributions/gaussian.rs

The convention of what `self.variance` means in this struct is inconsistent. The struct definition defines it as "squared scale", as with the [Wikipedia page](https://en.wikipedia.org/wiki/Normal_distribution). The pdf with this convention is then defined 
$$f(x) = \frac{\exp( -\frac{(x-\mu)^2}{2\sigma^2})}{\sigma \sqrt{2\pi}}.$$
In particular, `self.variance` should not be squared in exponential. Similarly an inconsistency was found in the implementation of `Distribution::cf()`.
Note the old formulas passed tests because tests were run for $\sigma^2 = 1$, which is obviously constant upon taking powers.

Fix Gaussian statistics. Convention used here is self.variance = sigma^2

---

src/portfolio.rs

solves #169.
Storing target weights inside of the portfolio seemed a bit off to me, could use an option there but I believe it's better to have that information in the user's rebalancing logic.
There were two approaches that I thought about:
- Store weights on the portfolio and keep the weights updated with each transaction & price tick
- Compute weights on the fly when needed
I've picked the second option since most applications have price ticks & transactions more frequently than accessing the portfolio weights (e.g. for rebalancing).

feat: Add portfolio.position_weights()

---

src/instruments/options/finite_difference_pricer.rs
src/instruments/options/mod.rs

This Pull Request is regarding issue https://github.com/avhz/RustQuant/issues/98 for the creation of a finite difference pricer. 
**I have made 2 PRs for this particular issue.** **_Only one of them needs to be merged if the decision has been made to merge._**
This PR uses heap allocated vectors to represent vectors and matrices with functions to handle the appropriate linear algebra calculations (+ matrix multiplication has been optimised for tridiagonal matrices). [The other PR utilises the nalgebra package.](https://github.com/avhz/RustQuant/pull/212)
**_The way in which the objects and methods should be used are exactly the same for both PRs._**
There are differences in speed performance between the two implementations.
An example with the following parameters:
```
initial_price: …
```

Finite Difference Pricer using heap allocated vectors

---

src/math/interpolation/exponential_interpolator.rs
src/math/interpolation/linear_interpolator.rs

Fixed the exponential interpolator.
https://github.com/avhz/RustQuant/pull/162#issuecomment-1926279538
One of the changes was in the actual computation to the exponential interpolation. I'm not too sure how your method previously worked, but the following method is quite straightforward, and it seems to fix the issue.
Method:
0. Starting with `(x_1, y_1)` and `(x_2, y_2)` and we want to interpolate at some point `x_1 < p < x_2`.
1. Take the `log` of the y-values. That is, we now have `(x_1, ln(y_1))` and `(x_2, ln(y_2))`.
2. Use linear interpolation between these two points.
3. Apply `exp` to it to convert back out of logspace.

Fixed the exponential interpolator

---

src/instruments/options/finite_difference_pricer.rs

This PR is for addressing the issues raised by @avhz in [this comment](https://github.com/avhz/RustQuant/issues/98#issuecomment-2078053371) - the code in question was initially merged from [this PR](https://github.com/avhz/RustQuant/pull/211) to address  [issue 98](https://github.com/avhz/RustQuant/issues/98).
There were some errors in implementation, namely:
- Call/Put boundary conditions had implemented $e^{-rT - t}$ instead of $e^{-r(T - t)}$
- The time steps were iterating `(1..self.time_steps)` instead of `(0..self.time_steps)`
- The boundary condition for the Crank-Nicolson method was implemented as `self.call_boundary(t + 1, T, delta_t)
- self.call_boundary(t, T, delta_t)` when it should be `self.call_boundary(t + 1, T, delta_t)
+ self.call_boundary(t, T, delta_t)` (same amendment …

Finite difference pricer adjustments

---

README.md

- Reflect changes from commit #853050d in the module table:
- Moved `quotes` and `cashflows` to `cashflows` module
- Moved `Money` implementation to `instruments` module
- Updated descriptions and merged sentences for `instruments` module
- Added links to ISO specifications in the `iso` module description
- Fixed underscored whitespaces between badges

docs: update module table and fix badge whitespaces, resolves #249

---

src/time/countries/europe/netherlands.rs
src/time/countries/mod.rs

Implementation of dutch calendar for #142 using the [official holidays](https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands).

Add Netherlands calendar

---

src/pricer/backends/bachelier.rs

The Modified Bachelier implementation here had a mistake that affected the order of operations. The following brings it inline with values from another library and CME QuikStrike.
See #267 for more information.

Fix for Modified Bachelier pricing. Closes #267

---

crates/RustQuant_time/src/countries/mod.rs
crates/RustQuant_time/src/countries/north_america/mexico.rs

Added Mexico Calendar and Complied with the tests 
#142

added Mexico calendar and tests

---

crates/RustQuant_time/Cargo.toml
crates/RustQuant_time/src/countries/middle_east/israel.rs
crates/RustQuant_time/src/countries/mod.rs

Hey guys,
I added support for the Israeli stock exchange and Jewish calendar as in #142 .
The Israeli stock exchange follows Jewish calendar which isn't in sync with our usual Gregorian calendar, so every year the holiday dates shift (e.g. Passover eve was in April 5th 2023, but April 22nd on 2024). I tried to solve it using a call to an external API that answers if a given day is a holiday.
Please let me know what you think and provide lots of criticism! I'm trying to learn and want to progress to more issues. 
Also, I noticed that two utility tests don't pass (unrelated to my changes):
`test crates/RustQuant_time/src/utilities.rs - utilities::unpack_date (line 20) ... ignored`
`test crates/RustQuant_time/src/utilities.rs - utilities::leap_year_count (line 118) ... FAILED`
Should I look …

Basic support for Israel (Jewish) Calander

---

crates/RustQuant_cashflows/src/quotes.rs

Hi there! 👋 
I’ve been experimenting with the library and noticed that the `set_value` function of `SimpleQuote` could use a bit more clarity in its documentation. Since the function returns the difference, I thought it would be helpful to make that more explicit.
Additionally, I spotted an issue where the `reset` function wasn’t resetting the value of the quote due to the match arm. I’ve included a fix for that as well.
Looking forward to your feedback—hope this helps!

quote.rs - documentation improvement and small fix

---

crates/RustQuant_error/src/lib.rs
crates/RustQuant_math/src/interpolation/b_splines.rs
crates/RustQuant_math/src/interpolation/mod.rs

This pull request is to address issue https://github.com/avhz/RustQuant/issues/5 and is part of the roadmap to v1 (https://github.com/avhz/RustQuant/issues/187).
B-splines are constructed by joining polynomials of degree $d$, resulting in a curve with continuity $C^{d-1}$.
For a B-spline of degree $d$, we define a set of control points:
$$C= [c_0, c_1, \ldots, c_{k-1}]$$
We also define a non-decreasing sequence of knots:
$$T = [t_0, t_1, \ldots, t_{k+d}]$$
where we require a total of $d + k + 1$ knots.
The basis functions are defined as follows:
$$
N_{i, 0}(t) = \begin{cases} 
1 & t\in[t_i, t_{i+1}) \\
0 & \text{otherwise}
\end{cases}
$$
$$
N_{i, d}(t) = \frac{t-t_i}{t_{i + d} - t_{i}} B_{i, d-1}(t) + \frac{t_{i+d+1} - t}{t_{i+d+1} - t_{i+1}} B_{i+1, d-1}(t)
$$
for …

B-Spline Interpolation Implementation

---

crates/RustQuant_instruments/Cargo.toml
crates/RustQuant_instruments/src/options/longstaff_schwartz.rs
crates/RustQuant_instruments/src/options/mod.rs

Pull request contributes to [this issue](https://github.com/avhz/RustQuant/issues/4) regarding pricers for American options.
The [Longstaff-Schwartz](https://people.math.ethz.ch/~hjfurrer/teaching/LongstaffSchwartzAmericanOptionsLeastSquareMonteCarlo.pdf) method is a Monte Carlo technique that uses least squares regression on in-the-money paths at each backwards time step to estimate the continuation value (the option’s value if it is not exercised).
In this implementation, I chose Legendre polynomials up to order 4 (i.e., orders 0 to 4) as the basis functions for the regression step. However, other basis functions, such as Hermite or Chebyshev, can also be used.
The unit tests were designed to pass within a tolerance threshold due to the variance in this method’s outcomes.
Note that at …

Longstaff-Schwartz Method for Pricing American Options

---

crates/RustQuant_instruments/src/monte_carlo_pricer.rs
crates/RustQuant_instruments/src/options/vanilla.rs
crates/RustQuant_stochastics/src/arithmetic_brownian_motion.rs
crates/RustQuant_stochastics/src/black_derman_toy.rs
crates/RustQuant_stochastics/src/brownian_motion.rs
crates/RustQuant_stochastics/src/constant_elasticity_of_variance.rs
crates/RustQuant_stochastics/src/cox_ingersoll_ross.rs
crates/RustQuant_stochastics/src/extended_vasicek.rs
crates/RustQuant_stochastics/src/fractional_brownian_motion.rs
crates/RustQuant_stochastics/src/fractional_cox_ingersoll_ross.rs
crates/RustQuant_stochastics/src/fractional_ornstein_uhlenbeck.rs
crates/RustQuant_stochastics/src/fractional_process.rs
crates/RustQuant_stochastics/src/geometric_brownian_bridge.rs
crates/RustQuant_stochastics/src/geometric_brownian_motion.rs
crates/RustQuant_stochastics/src/ho_lee.rs
crates/RustQuant_stochastics/src/hull_white.rs
crates/RustQuant_stochastics/src/lib.rs
crates/RustQuant_stochastics/src/merton_jump_diffusion.rs
crates/RustQuant_stochastics/src/monte_carlo.rs
crates/RustQuant_stochastics/src/ornstein_uhlenbeck.rs
crates/RustQuant_stochastics/src/process.rs
crates/RustQuant_stochastics/src/simulation.rs
examples/examples/custom_payoffs.rs
examples/examples/custom_process.rs
examples/examples/monte_carlo_pricing.rs
examples/examples/stochastic_processes.rs

This Pull Request was created to address [issue 244](https://github.com/avhz/RustQuant/issues/244).
With these latest changes, the emphasis was on implementing the Monte-Carlo only once - so that we would only need to update the code in one place should we need to amend anything regarding the algorithm.
The following changes have been made:
- The `euler_maruyama()` method has been replaced with `monte_carlo()`
- The type of scheme (Euler-Maruyama, Milstein etc) can be chosen via the `StochasticScheme` enum as a parameter for `StochasticConfig`
- Monte-Carlo engine centralised in a private (public crate-wide) function `run_monte_carlo()` in `monte_carlo.rs`
- Jump diffusion processes have a simplified Monte-Carlo implementation (no need to reimplement the algorithm)
- The Monte-Carlo …

Monte-Carlo Engine, seed parameter implementation and new numerical schemes for SDEs
